apiVersion: v1
kind: Service
metadata:
  name: elasticservice
  labels:
    app: elasticomics
spec:
  ports:
  - port: 9600
    name: elastic
  clusterIP: None
  selector:
    app: elasticomics
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
spec:
  serviceName: elasticservice
  replicas: 1
  selector:
    matchLabels:
      app: elasticomics
  template:
    metadata:
      labels:
        app: elasticomics
    spec:
      containers:
      - name: elastic
        image: blacktop/elasticsearch:5.6
        ports:
        - containerPort: 9600
          name: elastic
        volumeMounts:
        - name: elasticvol
          mountPath: /home/gaur/elasticvol
  volumeClaimTemplates:
  - metadata:
      name: elasticvol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
