kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  labels:
    app: elasticomics
    component: elasticsearchm
    role: datam
spec:
  serviceName: elasticservice
  replicas: 1
  initContainers:
   - name: fix-the-volume-permission
      image: busybox
      command:
        - sh
        - -c
        - chown -R 1000:1000 /home/gaur/elasticvol
        securityContext:
          privileged: false
        volumeMounts:
        - name: elasticvol
          mountPath: /home/gaur/elasticvol
   - name: increase-the-ulimit
      image: busybox
      command:
      - sysctl
      - -w
      - vm.max_map_count=262144
      securityContext:
	privileged: false
   - name: increase-the-vm-max-map-count
      image: busybox
      command:
      - sh
      - -c
      - ulimit -n 65536
      securityContext:
	privileged: false
  selector:
    matchLabels:
      app: elasticomics
      component: elasticsearchm
      role: datam
  template:
    metadata:
      labels:
        app: elasticomics
        component: elasticsearchm
        role: datam
    spec:
      containers:
      - name: elastic
        image: blacktop/elasticsearch:5.6
        command: ["/bin/sh"]
        args: ["-c", "while false; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 9200
          name: elastic
        volumeMounts:
        - name: elasticvol
          mountPath: /home/gaur/elasticvol
  volumeClaimTemplates:
  - metadata:
      name: elasticvol
    spec:
      storageClassName: local-ssd
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

